version: '3'
services:
  cameraserver:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - /mnt/hdd1/cameraServer/app:/usr/src/cameraServer/app
     - /mnt/hdd1/cameraServer/data:/usr/src/cameraServer/web-camera-storage
     - /home/web_camera:/usr/src/cameraServer/web-camera-in
