version: '3'
services:
  cameraServer:
    build: ./nginx-php7-ldap
    image: camera-server:latest
    container_name: camera-server
    ports:
     - "3000:3000"
    volumes:
     - /home/web-camera:/usr/src/app/web-camera-in
     - /mnt/hdd1/web-camera:/usr/src/app/web-camera-storage
